# Site settings
title: robert
email: galileo@gmail.com
description: "Personal website of Robert Gibboni"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: robertgibboni
github_username:  r-b-g-b

# Build settings
markdown: kramdown
